// APItool
// This header is generated by APItool. Do not modify it.

typedef struct {
 char* description;
 char* returns;
 char** argsarray_docs;
} APItool_Function_docs;

typedef struct {
 char* funcname;
 char* returntype;
 int argsarray_len;
 char** argsarray_names;
 char** argsarray_types;
 APItool_Function_docs* doc;
} APItool_Function;

typedef struct {
 char* varname;
 char* type;
 char* doc_description;
} APItool_Variable;

typedef enum  {
 APItool_TYPEDEF,
 APItool_IMMEDIATE,
 APItool_TYPEDEF_IMMEDIATE
} APItool_typedef_status;

typedef struct {
 char* description;
 char** typesarray_docs;
} APItool_Struct_Union_Enum_docs;

typedef struct {
 char* sunname;
 int typesarray_len;
 char** typesarray_names;
 char** typesarray_types;
 APItool_typedef_status marked;
 APItool_Struct_Union_Enum_docs* doc;
 bool isunion;
} APItool_Struct_Union;

typedef struct {
 char* enumname;
 int array_len;
 char** array_names;
 APItool_typedef_status marked;
 APItool_Struct_Union_Enum_docs* doc;
} APItool_Enum;

typedef union {
 char* verbatim;
 APItool_Function* func;
 APItool_Variable* var;
 APItool_Struct_Union* sun;
 APItool_Enum* enm;
} APItool_token_value;

typedef enum  {
 APItool_FUNCTION,
 APItool_VERBATIM,
 APItool_VARIABLE,
 APItool_STRUCT_UNION,
 APItool_ENUM
} APItool_token_type;

typedef struct {
 APItool_token_value token;
 APItool_token_type tt;
} APItool_token;

typedef struct {
 APItool_token** val;
 int numtokens;
} APItool_AST;

void APItool_gen_pair(APItool_AST* src, char* headerdest, char* htmldest, char* progname);

APItool_AST* APItool_parse_file(char* fname);

void APItool_freeAST(APItool_AST* a);

