void APItool_gen_pair(APItool_AST* src, char* headerdest, char* htmldest, char* progname) {

 // This part generates the header

 FILE* header = fopen(headerdest, "w");
 fprintf(header, "// %s\n", progname);
 fputs("// This header is generated by APItool. Do not modify it.\n\n", header);
 for(int i = 0; i < src->numtokens; i++) {
  APItool_token* ct = src->val[i];
  switch(ct->tt) {
   case APItool_FUNCTION:;
    APItool_Function* func = ct->token.func;
    char* ssb = S_strip_backtick(func->returntype);
    fputs(ssb, header);
    free(ssb);
    putc(' ', header);
    fputs(func->funcname, header);
    putc('(', header);
    for(int i = 0; i < func->argsarray_len; i++) {
     ssb = S_strip_backtick(func->argsarray_types[i]);
     fputs(ssb, header);
     free(ssb);
     putc(' ', header);
     fputs(func->argsarray_names[i], header);
     if(i < func->argsarray_len-1) {
      putc(',', header);
      putc(' ', header);
     }
    }
    putc(')', header);
    putc(';', header);
    putc('\n', header);
    break;
   case APItool_VERBATIM:;
    fputs(ct->token.verbatim, header);
    putc('\n', header);
    break;
   case APItool_VARIABLE:;
    APItool_Variable* var = ct->token.var;
    fputs(S_strip_backtick(var->type), header);
    putc(' ', header);
    fputs(var->varname, header);
    putc(';', header);
    putc('\n', header);
    break;
   case APItool_STRUCT_UNION:;
    APItool_Struct_Union* sun = ct->token.sun;
    if(sun->marked != APItool_IMMEDIATE) {
     fputs("typedef ", header);
    }
    fputs(sun->isunion ? "union " : "struct ", header);
    if(sun->marked != APItool_TYPEDEF) {
     fputs(sun->sunname, header);
    }
    putc('{', header);
    putc('\n', header);
    for(int i = 0; i < sun->typesarray_len; i++) {
     putc(' ', header);
     char* ssb = S_strip_backtick(sun->typesarray_types[i]);
     fputs(ssb, header);
     free(ssb);
     putc(' ', header);
     fputs(sun->typesarray_names[i], header);
     putc(';', header);
     putc('\n', header);
    }
    putc('}', header);
    if(sun->marked != APItool_IMMEDIATE) {
     putc(' ', header);
     fputs(sun->sunname, header);
    }
    putc(';', header);
    putc('\n', header);
    break;
   case APItool_ENUM:;
    APItool_Enum* enm = ct->token.enm;
    if(enm->marked != APItool_IMMEDIATE) {
     fputs("typedef ", header);
    }
    fputs("enum ", header);
    if(enm->marked != APItool_TYPEDEF) {
     fputs(enm->enumname, header);
    }
    putc(' ', header);
    putc('{', header);
    putc('\n', header);
    for(int i = 0; i < enm->array_len; i++) {
     putc(' ', header);
     fputs(enm->array_names[i], header);
     if(i < enm->array_len-1) {
      putc(',', header);
     }
     putc('\n', header);
    }
    putc('}', header);
    if(enm->marked != APItool_IMMEDIATE) {
     putc(' ', header);
     fputs(enm->enumname, header);
    }
    putc(';', header);
    putc('\n', header);
    break;
   default: break;
  }
  putc('\n', header);
 }

 // This part generates the html

 FILE* html = fopen(htmldest, "w");
 fprintf(html,
  "<!DOCTYPE html>\n"
  "<html>\n"
  "<head>\n"
  " <title>APItool documentation for %s</title>\n"
  " <style>.token { border: 2px solid black; } </style>\n"
  "</head>\n"
  "<body>\n"
  " <h2>APItool documentation for %s</h2>\n"
  ,progname,progname
 );
 for(int i = 0; i < src->numtokens; i++) {
  APItool_token* ct = src->val[i];
  switch(ct->tt) {
   case APItool_FUNCTION:;
    APItool_Function* func = ct->token.func;
    fprintf(html,
     " <div class='token'>\n"
     "  <h3>Section %d (function): %s</h3>\n"
     ,i,func->funcname
    );
    if(func->doc->description) {
     fprintf(html,
      "  <p>%s</p>\n"
      ,func->doc->description
     );
    }
    char* rtrn = S_type_linker(func->returntype, src);
    fprintf(html,
     "  <p>\n"
     "   returns %s\n"
     ,rtrn
    );
    free(rtrn);
    if(func->doc->returns) {
     fprintf(html,
      "   <br>\n"
      "   <span>%s</span>\n"
      ,func->doc->returns
     );
    }
    fputs("  </p>\n", html);
    if(func->argsarray_len > 0) {
     fputs("  <b>args:</b>\n"
           "  <dl>\n", html);
     for(int j = 0; j < func->argsarray_len; j++) {
      char* typ = S_type_linker(func->argsarray_types[j], src);
      fprintf(html,
       "   <dt>%s %s</dt>\n"
       "   <dd>%s</dd>\n"
       ,typ,func->argsarray_names[j], (func->doc->argsarray_docs[j] ? func->doc->argsarray_docs[j] : "") // if there aren't docs for this arg well who cares
      );
      free(typ);
     }
     fputs("  </dl>\n", html);
    }
    fputs(" </div>\n", html);
    break;
   case APItool_VARIABLE:;
    APItool_Variable* var = ct->token.var;
    fprintf(html,
     " <div class='token'>\n"
     "  <h3>Section %d (variable): %s</h3>\n"
     "  <p>type is %s</p>\n"
     ,i,var->varname,var->type
    );
    if(var->doc_description) {
     fprintf(html,
      "  <p>%s</p>\n"
      ,var->doc_description
     );
    }
    fputs(" </div>\n", html);
    break;
   case APItool_STRUCT_UNION:;
    APItool_Struct_Union* sun = ct->token.sun;
    fprintf(html,
     " <div class='token'>\n"
     "  <h3>Section %d (%s): %s</h3>\n"
     ,i,sun->isunion?"union":"struct",sun->sunname
    );
    if(sun->doc->description) {
     fprintf(html,
      "  <p>%s</p>\n"
      ,sun->doc->description
     );
    }
    if(sun->typesarray_len > 0) {
     fputs("  <b>fields:</b>\n"
           "  <dl>\n", html);
     for(int j = 0; j < sun->typesarray_len; j++) {
      char* typx = S_type_linker(sun->typesarray_types[j], src);
      fprintf(html,
       "   <dt>%s %s</dt>\n"
       "   <dd>%s</dd>\n"
       ,typx,sun->typesarray_names[j], (sun->doc->typesarray_docs[j] ? sun->doc->typesarray_docs[j] : "")
      );
      free(typx);
     }
     fputs("  </dl>\n", html);
    }
    fputs(" </div>\n", html);
    break;
   case APItool_ENUM:;
    APItool_Enum* enm = ct->token.enm;
    fprintf(html,
     " <div class='token'>\n"
     "  <h3>Section %d (enum): %s</h3>\n"
     ,i,enm->enumname
    );
    if(enm->doc->description) {
     fprintf(html,
      "  <p>%s</p>\n"
      ,enm->doc->description
     );
    }
    if(enm->array_len > 0) {
     fputs("  <b>values:</b>\n"
           "  <dl>\n", html);
     for(int j = 0; j < enm->array_len; j++) {
      fprintf(html,
       "   <dt>%s</dt>\n"
       "   <dd>%s</dd>\n"
       ,enm->array_names[j], (enm->doc->typesarray_docs[j] ? enm->doc->typesarray_docs[j] : "")
      );
     }
     fputs("  </dl>\n", html);
    }
    fputs(" </div>\n", html);
    break;
   default: break;
  }
 }
 fputs(
  "</body>\n"
  "</html>\n",
  html
 );
}
